### PR TITLE
Add contribution notice

### PR DESCRIPTION
**Pull request by mnieper**

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Good idea.  Merged and pushed.

**Comment by mnieper** [comment]
Good morning, by the way!  My day just started.

Am Di., 15. Nov. 2022 um 07:34 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

**Comment by arthurgleckler** [comment]
Good evening!  I didn't make much progress on 242, but I'm looking forward to working on it tomorrow.

**Comment by mnieper** [comment]
Am Di., 15. Nov. 2022 um 07:41 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

> Good evening! I didn't make much progress on 242, but I'm looking forward
> to working on it tomorrow.
>

I hope that the new subsection is helpful.

**Pull request merged**
